openapi: 3.1.0
info:
  title: MOVIES
  version: '1.0'
  summary: API for movies
  description: API for movies
servers:
  - url: 'http://localhost:5000'
paths:
  /auth:
    parameters: []
    post:
      summary: 'The route to log in a user'
      operationId: post-auth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
              examples:
                Users token:
                  value:
                    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyMywibmFtZSI6IkJhc2ljIFRob21hcyIsInJvbGUiOiJiYXNpYyIsImlhdCI6MTY0NTYzNDk5NywiZXhwIjoxNjQ1NjM2Nzk3LCJpc3MiOiJodHRwczovL3d3dy5uZXRndXJ1LmNvbS8iLCJzdWIiOiIxMjMifQ.QYeqCeTqVUNBtqvt2P0JyHiRF1dAnKbCOjNHrPHNEso
      description: Logs in a user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
            examples:
              The details of the user:
                value:
                  username: basic-thomas
                  password: sR-_pcoow-27-6PAwCD8
        description: The log in details of the user
  /movies:
    parameters: []
    get:
      summary: 'The route to fetch all movies'
      operationId: get-movies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        userId:
                          type: string
                        Title:
                          type: string
                        Released:
                          type: string
                        Genre:
                          type: string
                        Director:
                          type: string
                        createdAt:
                          type: string
                        updatedAt:
                          type: string
      description: Get all the saved movies.
      parameters: []
    post:
      summary: 'The route to create new movie'
      operationId: post-movies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      userId:
                        type: string
                      Title:
                        type: string
                      Released:
                        type: string
                      Genre:
                        type: string
                      Director:
                        type: string
                      _id:
                        type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
      description: Create a new movie
      parameters:
        - schema:
            type: string
          in: header
          name: authorization
          description: It holds the authorization Bearer Token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
            examples:
              Save the movie title to database:
                value:
                  title: Intricate
components:
  schemas: {}
